export const REST_SERV = {
    loginUrl: 'https://www.lukaksarticles.com/login',
    pubsUrl: 'https://www.lukaksarticles.com/publication',
    pubFilterUrl: 'https://www.lukaksarticles.com/publication/filter',
    qTypeUrl: 'https://www.lukaksarticles.com/qtype',
    commentUrl: 'https://www.lukaksarticles.com/comment',
    relevanceUrl: 'https://www.lukaksarticles.com/relevance',
    mediaBack: 'http://back.lukaksarticles.com:8080',
    pushSub: 'http://ec2-18-228-7-103.sa-east-1.compute.amazonaws.com:3003/subscribe',
    socketServerUrl: 'https://www.lukaksarticles.com',
    webRtcSocketServerUrl: 'ws://18.228.114.178:8080//lukaskstreaming',
    userUrl: 'https://www.lukaksarticles.com/user/',
    notifUrl: 'https://www.lukaksarticles.com/notification',
    paymentPay: 'https://www.lukaksarticles.com/payment/pay',
    paymentCard: 'https://www.lukaksarticles.com/payment/card',
    cancelado: 'https://www.lukaksarticles.com/payment/cancelado',
    exitoso: 'https://www.lukaksarticles.com/payment/exitoso',
    signUrl: 'https://www.lukaksarticles.com/signIn/',
    provinceUrl: 'https://www.lukaksarticles.com/province',
    cantonUrl: 'https://www.lukaksarticles.com/canton',
    parroquiaUrl: 'https://www.lukaksarticles.com/parroquia'
}
