export const CONTENT_TYPES = {
    new_media: 0,
    new_pub: 1,
    edit_queja: 2,
    view_queja: 3,
    alert: 4,
    view_replies: 5,
    edit_profile: 6,
    comment_input: 7,
    single_map: 8,
    view_img: 9,
    view_comments: 10,
    new_notification: 11,
    view_notifs: 12,
    view_transmission: 13,
    support_list: 14,
    find_accounts: 15,
    planilla_detail: 16,
    payment_card: 17,
    paypal: 18,
    register_profile: 19
}