export const CONTENT_TYPES = {
    new_media: 0,
    new_pub: 1,
    edit_queja: 2,
    view_queja: 3,
    alert: 4,
    view_replies: 5,
    edit_profile: 6,
    comment_input: 7,
    single_map: 8,
    view_img: 9,
    view_comments: 10,
    new_notification: 11,
    view_notifs: 12,
    view_transmission: 13,
}