/** VAPID KEY TO SUBSCRIBE TO BACKEND SERVER */
//NEXT IS THE PUBLIC KEY GENERATED IN OUR BACKEND NODE.JS SERVER:
export var VAPID_KEY = "BF7zMOGFjtbomZsVXobu1T_c2L3ADR8-DTI0dd1XfNcGlDzifqEKzuygCREHPOQtOrvHbL8nM2Skk53PsAGdauE";
/////